# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_policy_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19game_policy_service.proto\x12\x07\x65xample\",\n\x0cInferRequest\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\x0c\"\x1d\n\nInferReply\x12\x0f\n\x07message\x18\x01 \x01(\x0c\"\x1f\n\x0cResetRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nResetReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x98\x01\n\x11GamePolicyService\x12@\n\x10game_policy_step\x12\x15.example.InferRequest\x1a\x13.example.InferReply\"\x00\x12\x41\n\x11game_policy_reset\x12\x15.example.ResetRequest\x1a\x13.example.ResetReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_policy_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFERREQUEST']._serialized_start=38
  _globals['_INFERREQUEST']._serialized_end=82
  _globals['_INFERREPLY']._serialized_start=84
  _globals['_INFERREPLY']._serialized_end=113
  _globals['_RESETREQUEST']._serialized_start=115
  _globals['_RESETREQUEST']._serialized_end=146
  _globals['_RESETREPLY']._serialized_start=148
  _globals['_RESETREPLY']._serialized_end=177
  _globals['_GAMEPOLICYSERVICE']._serialized_start=180
  _globals['_GAMEPOLICYSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
