# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from werewolf.helper.grpc_service import game_policy_service_pb2 as game__policy__service__pb2


class GamePolicyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.game_policy_step = channel.unary_unary(
                '/example.GamePolicyService/game_policy_step',
                request_serializer=game__policy__service__pb2.InferRequest.SerializeToString,
                response_deserializer=game__policy__service__pb2.InferReply.FromString,
                )
        self.game_policy_reset = channel.unary_unary(
                '/example.GamePolicyService/game_policy_reset',
                request_serializer=game__policy__service__pb2.ResetRequest.SerializeToString,
                response_deserializer=game__policy__service__pb2.ResetReply.FromString,
                )


class GamePolicyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def game_policy_step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def game_policy_reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GamePolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'game_policy_step': grpc.unary_unary_rpc_method_handler(
                    servicer.game_policy_step,
                    request_deserializer=game__policy__service__pb2.InferRequest.FromString,
                    response_serializer=game__policy__service__pb2.InferReply.SerializeToString,
            ),
            'game_policy_reset': grpc.unary_unary_rpc_method_handler(
                    servicer.game_policy_reset,
                    request_deserializer=game__policy__service__pb2.ResetRequest.FromString,
                    response_serializer=game__policy__service__pb2.ResetReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.GamePolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GamePolicyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def game_policy_step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.GamePolicyService/game_policy_step',
            game__policy__service__pb2.InferRequest.SerializeToString,
            game__policy__service__pb2.InferReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def game_policy_reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.GamePolicyService/game_policy_reset',
            game__policy__service__pb2.ResetRequest.SerializeToString,
            game__policy__service__pb2.ResetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
